export const Courses = [
    {
        "name": "BUSINESS/ACCOUNTANCY/STATISTICS",
        "values": [
            "Peachtree Accounting",
            "QuickBook",
            "SPSS",
            "Advanced Microsoft Access",
            "Advance Microsoft Excel",
            "Advanced Microsoft Office PowerPoint Presentation",
        ]
    },

    {
        "name": "ENGINEERING/ARCHITECTURAL/\nSTRUCTURAL",
        "values": {
            "AutoCAD 2D for Architectural/mechanical drafting and design": ["AutoCAD 2D for Architectural/mechanical drafting and design"],
            "AutoCAD 2D & 3D for Architectural/Mechanical Drafting & design": ["AutoCAD 2D & 3D for Architectural/Mechanical Drafting & design"],
            "AutoCAD 2D & 3D for Advanced  Architectural / Mechanical Design Modeling": ["AutoCAD 2D & 3D for Advanced  Architectural / Mechanical Design Modeling"],
            "Google SketchUP 3D BIM & Rendering": ["Google SketchUP 3D BIM & Rendering"],
            "ArchiCAD 3D BIM & Rendering": ["ArchiCAD 3D BIM & Rendering"],
            "Revit Architectural 3D BIM & Rendering": ["Revit Architectural 3D BIM & Rendering"],
            "Autodesk 3d Max (Modeling/Rendering/Animation)": ["Autodesk 3d Max (Modeling/Rendering/Animation)"],
            "Autodesk Maya (Modelling/Rendering/Animation)": ["Autodesk Maya (Modelling/Rendering/Animation)"]
        }
    },

    {
        "name": "COMPUTER ENGINEERING",
        "values": {
            "Cisco (CCNA Training) + COURSE MATERIALS": ["Cisco (CCNA Training) + COURSE MATERIALS"],
            "Networking (in line with Comptia N+)": ["Networking (in line with Comptia N+)"],
            "Networking + (cyber café management and administration)": ["Networking + (cyber café management and administration)"],
            "Computer Engineering (in line with Comptia N+)": ["Computer Engineering (in line with Comptia N+)"]
        }
    },

    {
        "name": "DIGITAL SECURITY",
        "values": {
            "CCTV/IP Surveillance": ["CCTV/IP Surveillance"],
            "PABX & Intercom System": ["PABX & Intercom System"],
            "VSAT Field Engineering": ["VSAT Field Engineering"],
            "Electric Fencing": ["Electric Fencing"],
            "Radio Message": ["Radio Message"],
            "Car Tracking and Fleet Management": ["Car Tracking and Fleet Management"],
            "Biometric and Access Control Management": ["Biometric and Access Control Management"]
        }
    },

    {
        "name": "VOCATIONAL TRAINING",
        "values": {
            "Auto Mechanic": [
                "Automotive Control, ",
                "Automotive Service Technician,",
                "Automotive Technical Studies, "
            ],
            "Building and Construction": [
                "Carpentry, ",
                "Heating and Air Condition, ",
                "Plumbing, ",
                "Structured Cabling, ",
                "Welding, ",
                "Locksmith, "
            ],
            "Fashion & Beauty": [
                "Make-up and hair design, ",
                "Fashion Media, ",
                "Fashion Photography, ",
                "Massage Therapist, ",
                "Cosmetologist, ",
                "Beautician"
            ],
            "Photography": ["Photography"],
            "Manufacturing, Transportation and Logistics": [
                "Inventory control, ",
                "Professional truck driver, ",
                "Warehouse and distribution, ",
                "Health and environmental safety"
            ]
        }
    },

    {
        name: 'ELECTRICAL ENGINEERING',
        values: [
            'Electrical & Electronics Technician',
            'Electrical and Electronics',
            'Electrical Engineering Technology',
            'Structured Cabling',
            'Engineering Design and Drafting Technology',
        ]
    },
    {
        name: 'ENTREPRENEURSHIP STUDIES ',
        values: [
            'A.\tBusiness and Marketing Management',
            'B.\tInnovation and Creativity in Business',
            'C.\tHuman Resource Management',
            'D.\tCooperate Culture and Entrepreneurship',
            'E.\tAccounting & Finance Management',
            'G.\tEnterprise Planning, Appraisal & Financing',
            'H.\tBuilding Entrepreneurial Culture & Team',
            'I.\tOffice Administration',
        ]
    },
    {
        name: 'BUSINESS STUDIES COURSES',
        values: [
            'A.\tBusiness Administration',
            'B.\tBusiness Analysis',
            'C.\tBusiness Computing',
            'D.\tBusiness Ethics',
            'E.\tBusiness Statistics',
            'F.\tCommercial Law',
            'G.\tDeveloping Markets',
            'H.\tEconomic Principles',
            'I.\tFinance',
            'J.\tHuman Resources',
            'K.\tInternational Studies',
            'L.\tManagement',
            'M.\tMarketing',
            'N.\tOperations Management',
            'O.\tResearch and Technology',
        ]
    },
    {
        name: 'CONTENT AND SOCIAL MEDIA MARKETING MASTERY',
        values: [
            'Digital Marketing',
            'Content Creation and Video Ads',
            'Understanding everything about Social Media Marketing',
            'Create highly optimized and high quality paid Ads on all Social Media platforms',
            'Learn Instagram Marketing A-Z and how to monetize the social media platform',
            'Master YouTube Marketing including Layouts, Content Creation and Video ads',
            'Optimize your LinkedIn Profile and use LinkedIn ads to grow your business',
            'Use Web 2.0 Blogs to further expand your reach with SEO, and Content Marketing',
            'Learn Social Media Marketing posting via IFTTT',
            'Learn the Power of Pinterest promoted pins and all the Pinterest Marketing Strategies',
            'Use Goggle Business to benefit Local Business and help Search Engine Organization',
            'Become a Facebook ad Expert',
        ]
    },
    {
        name: 'PUBLIC ADMINISTRATION',
        values: [
            'A.\tInstitutional Development',
            'B.\tPolitical Science',
            'C.\tPublic Relations',
            'D.\tProject Finance and Public Private Partnerships',
            'E.\tManaging Public Money',
            'F.\tThe Science of Happiness at Work',
            'G.\tPeople Management',
            'H.\tHR and Payroll Management',
            'I.\tDigital Innovation for Civic Engagement Projects',
            'J.\tPublic Management and Governance in a Changing World',
        ]
    },
    {
        name: 'INFORMATION TECHNOLOGY MANAGEMENT',
        values: [
            'Data Science',
            'Data Analytics',
            'Cloud Computing',
            'A.\tProgramming Languages',
            '-\tJava',
            '-\tPHP',
            '-\tSQL',
            '-\tVisual Basic',
            '-\tQbasic',
            '-\tAssembly Language',
            '-\tVisual C ++ (GUI and CONSOLE)',
            '-\tAndroid Programming / Application Development',
            '-\tOracle & Scripting Language',
            'B.\tCyber Security',
            'C.\tDynamic Web Development',
            '-\tHTML',
            '-\tDreamweaver',
            '-\tAdobe Flash',
            '-\tJoomla',
            '-\tWeb Design Complete (Beginner – Advanced)',
            '-\tWeb Design Complete (Database Driven)',
            'D.\tGraphic Design, Photo Editing/Video Editing',
            '-\tAdvance Graphic Design (CorelDraw, Photo Paint & Photoshop)',
            '-\tPhotoshop',
            '-\tVideo Editing & Production',
            'E.\tCorel Draw',
            '1.\tIntroduction to CorelDraw',
            '-\tMeaning, Functions, Versions and Examples',
            '-\tExploring the CorelDraw screen and its features',
            '-\tSetup the Page and Plan your Drawing',
            '2.\tMoving around and viewing drawings',
            '-\tMoving around the current page',
            '-\tViewing modes',
            '-\tInserting and deleting pages',
            '-\tChanging pages',
            '3.\tSelecting and manipulating objects',
            '-\tSelecting and deselecting objects',
            '-\tMoving objects',
            '-\tCopying and deleting objects',
            '-\tDeleting objects',
            '-\tSizing objects',
            '4.\tDrawing and shaping objects',
            '-\tDrawing and shaping tools',
            '-\tUsing the freehand tool',
            '-\tDrawing lines and poly-lines',
            '-\tDrawing freehand polygons',
            '-\tDrawing perfect shapes',
            '-\tReshaping lines and poly-lines',
            '-\tDrawing curves',
            '-\tDrawing rectangles',
            '-\tDrawing circles',
            '5.\tArranging shapes',
            '-\tArranging objects',
            '-\tGrouping and ungrouping objects',
            '-\tUsing guidelines',
            '-\tUsing snap to',
            '-\tAligning objects',
            '6.\tWorking with Text',
            '-\tThe Text tool',
            '-\tCreating Artistic Text',
            '-\tEditing Text Formatting Text',
            '-\tSetting Text Options',
            '-\tCreating Paragraph Options',
            '-\tSetting Indents Using the Ruler',
            '-\tImporting Text',
            '-\tUsing the Spell Checker',
            '7.\tOutlining & Filling Objects',
            '-\tThe Outline Tool',
            '-\tChoosing Outline Thicknesses',
            '-\tChoosing Outline Colors',
            '-\tUsing Fill Tool',
            '-\tCopying Attributes',
            '-\tSetting Outline and Fill Defaults',
            '8.\tUsing Symbols and Clip art',
            '-\tInserting Text Symbols',
            '-\tAdding Clip art',
            '-\tModifying Clip art',
            '-\tUsing the Scrapbook to Search for Clip art',
            '9.\tTransforming Objects',
            '-\t Mirroring Objects',
            '-\tRotating and Skewing Objects',
            '-\tUsing Transform Dockers',
            '10.\tSpecial Effects',
            '-\tFitting Text to a Path',
            '-\tDrawing with the Artistic Media Tool',
            '-\tShaping an Object with an Envelope',
            '-\tExtruding an Object',
            '-\tUsing the Lens Effect',
            '-\tAdding Perspectives',
            '-\tUsing Power Clips',
            '-\tApplying Contours',
            '-\tApplying Drop Shadows',
            '11.\tImporting and Exporting',
            '-\tImporting images',
            '-\tCropping images',
            '-\tExporting to graphic formats',
            '12.\tPrinting',
            '-\tPrint Options',
            '-\tPrint Preview',
            '13\tComputer Operations',
            '-\tIntroduction to Computer',
            '-\tDefinition, characteristics and uses',
            '-\tTypes, History and generation',
            '-\tComponents',
            '(i.\tHARDWARE',
            'a.\tInput, Output, Storage and Peripheral Devices (Emphasis on Keyboard and Mouse)',
            'b.\tThe System Unit and its Components Motherboard, RAM and Processor',
            'c.\tOther Hardware Components: Expansion Cards, Ports & Connectors',
            '(ii.\tSOFTWARE',
            'a.\tSystem Software: The Operating System Function, Types, History & Development.',
            'b.\tApplication Software',
            'c.\tFirmware',
            '14\tExploring the GUI',
            '-\tDesktop, Taskbar and Start Menu',
            '-\tLaunching and Managing Programs',
            '-\tFiles, Folders and Shortcuts: Creating, Modifying, Copying, Hiding and Deleting',
            '-\tThe Recycle Bin',
            '-\tLibraries and Recent places',
            '15\tThe Control Panel',
            '-\tDesktop, Taskbar and Start Menu',
            '-\tLaunching and Managing Programs',
            '-\tFiles, Folders and Shortcuts: Creating, Modifying, Copying, Hiding and Deleting',
            '-\tThe Recycle Bin',
            '-\tLibraries and Recent places',
            '16\tThe Control Panel',
            '-\tUser Accounts: Concepts, Types, Creating, Modifying, Deleting and Privacy Control',
            '-\tPrograms',
            '(a.\tInstallation/Uninstall, Repair and upgrade',
            '(b.\tSetting default programs',
            '-\tSystem and Security',
            '(a.\tSystem Information',
            '(b.\tSystem Update and Rollback',
            '-\tHardware and Sound',
            '(a.\tAdding and Configuring Devices',
            '(b.\tThe Device Manager',
            '-\tNetwork and Sharing',
            '(a.\tSetting up a Network',
            '(b.\tConnecting to a Network',
            '(c.\tTroubleshooting Network Problems',
            '(d.\tTask Schedule',
            '17.\tPower Configuration and Management',
            '-\tPower Settings',
            '-\tSystem Refresh, Shutdown and Restart',
            '-\tSleep, Hibernation and Hybrid Sleep',
            '-\tPower up Modes: Normal and Safe Modes',
            '-\tBooting: The Boot Process and Boot Settings',
            '18\tIntroduction to Basic Windows Programs',
            '-\tMedia Player, Picture Manager and Paint',
            '-\tMicrosoft Office: Word, Excel, PowerPoint, Access, Publisher and Notepad',
            '-\tCore; Graphics Suite: Corel Capture, CorelDraw and Corel Photo-Paint',
            '19\tIntroduction to Network and the Internet',
            '-\tComputer Network',
            '(a.\tConcept, Components and Classification',
            '(b.\tServer and its Types',
            '(c.\tNetwork Topology',
            '(d.\tNetwork Layers',
            '-\tThe Internet',
            '(a.\tConcept, features and history',
            '(b.\tInternet protocols',
            '(c.\tBrowsing and Internet Browsers',
            '(d.\tSearching and the Search Engines',
            '20\tBasic Troubleshooting Techniques',
            '-\tConcept and approaches',
            '-\tBasic troubleshooting with Control Panel Applets (MMC, Defragmenter, Event Viewer, Registry Editor, Task Manager, System Restore etc.)',
        ]
    },
    {
        name: 'INTRODUCTION TO THE INTERNET',
        values: [
            '1.\tIntroduction to the Internet',
            '-\tIntranet, Internet and Extranet',
            '2.\tNetwork Devices and Topology',
            '-\tNetwork classification',
            '-\tNetwork topology',
            '-\tNetworking devices',
            '3.\tWeb browser and features',
            '4.\tOpening an email address',
            '5.\tSearch engines and utilization',
            '6.\tOnline services',
        ]
    },
    {
        name: 'MICROSOFT OFFICE WORD',
        values: [
            '1.\tIntroduction to Microsoft Word',
            '-\tMeaning, history, functions, types and examples',
            '2.\tScreen features of Microsoft Word',
            '3.\tCreating a New and Opening an Existing Word Document',
            '-\tCreating a new document',
            '-\tOpening an existing document',
            '-\tDifferent views in word',
            '-\tThe office assistant',
            '4.\tSetting up Documents',
            '-\tLayout',
            '-\tAdjusting margins',
            '5.\tModifying Text',
            '-\tMoving text around',
            '-\tBullets and numbering in word',
            '-\tAnimating text',
            '-\tFormatting text',
            '6.\tGraphics in Word',
            '-\tInserting clip art images',
            '-\tInserting file images',
            '-\tInserting a chart, smart art and graphs',
            '-\tFormatting clip art, images and charts',
            '-\tMoving and deleting images',
            '7.\tFormatting',
            '-\tInserting headers and footers',
            '-\tPage numbering',
            '-\tDrop caps, watermark and border page',
            '-\tInserting and formatting a column',
            '-\tText wrapping',
            '-\tAlignment',
            '-\tFind and replace',
            '-\tWord art and text box',
            '8.\tDrawing Tools',
            '-\tCreating lines and arrows',
            '-\tInserting shapes in your document',
            '-\tShadow effect',
            '-\tAdding borders to a picture',
            '-\tShape fill',
            '9.\tWord Tools',
            '-\tSpell check',
            '-\tThesaurus',
            '10.\tTables',
            '-\tCreating /inserting a table',
            '-\tDeleting a table',
            '-\tMoving a table',
            '-\tBorders on tables',
            '-\tShading a table',
            '-\tTable formatting',
            '-\tDeleting a table',
            '11.\tMiscellaneous Word Tasks',
            '-\tPrinting and print preview',
            '-\tSaving word documents',
            '-\tSaving a word document as a web page',
            '12.\tExercises/Practice',
        ]
    },
    {
        name: 'MICROSOFT OFFICE EXCEL',
        values: [
            '1.\tIntroduction to Electronic Spread Sheet And Excel',
            '-\tMeaning, history, function, types and examples',
            '2.\tIntroduction to Microsoft excel window and its features',
            '3.\tEntering Microsoft Excel Data and Formatting Data',
            '-\tEntering data into excel environment',
            '-\tTypes of data ',
            '-\tFormatting data in excel',
            '-\tInserting and deleting columns and rows',
            '-\tInserting charts and graphics',
            '4.\tEntering Microsoft Excel Formulas',
            '-\tPerforming mathematical calculations',
            '-\tPerforming automatic calculations',
            '-\tPerforming advanced mathematical calculations',
            '5.\tCreating Excel Functions and Filling Cells',
            '-\tUsing Reference Operators',
            '-\tFormatting Functions',
            '-\tFormatting Worksheet',
            '-\tFilter / Sort, Named Ranges',
            '6.\tStatistical Calculation',
            '7.\tLogical Calculation',
            '8.\tFinancial Calculation',
            '9.\tMiscellaneous Excel Tasks',
            '-\tPrinting and Print Preview',
            '-\tSaving Excel Documents',
            '10.\tExercises/Practice',
        ]
    },
    {
        name: 'MICROSOFT OFFICE POWER POINT',
        values: [
            '1.\tIntroduction to PowerPoint Presentation Package',
            '-\tHistory, Functions, Versions and Examples',
            '2.\tIntroduction to PowerPoint Window',
            '3.\tCreating a PowerPoint Presentation',
            '-\tOpening a Presentation',
            '-\tChanging Views',
            '-\tInserting Slides',
            '-\tChanging Text Formats',
            '-\tSaving and Closing a Presentation',
            '4.\tInsert Menu',
            '-\tInsert a Picture',
            '-\tInsert a Chart',
            '-\tInsert a Smart Art',
            '-\tInsert a Word Art',
            '-\tInsert Headers and Footers',
            '5.\tIntroduction to Drawing Tools',
            '-\tInserting Shapes',
            '-\tInserting Shapes',
            '-\tAdding Texts to Shapes',
            '-\tFormatting Shapes',
            '-\tInserting Action Buttons/Hyperlinks',
            '6.\tAdding Effects',
            '-\tTransition Effects',
            '-\tAnimation Effects',
            '-\tSound Clips',
            '7.\tWorking in Outline View',
            '-\tImporting an Outline from Word',
            '-\tFinding  and Replacing Text',
            '-\tPrinting your Presentation',
            '8.\tCreating a Custom Show',
            '-\tRehearsing a Slide Show',
            '-\tRunning a Slide Show',
            '-\tExercises / Practice',
        ]
    },
    {
        name: 'MICROSOFT OFFICE ACCESS',
        values: [
            '1.\tIntroduction to Microsoft Access',
            '-\tMeaning, History, Types, Versions and examples of Database Management System',
            '2.\tIntroduction to Microsoft Access Window and its features',
            '3.\tMethods on how to load MS Access',
            '4.\tCreating Microsoft Access Tables',
            '5.\tWorking with Microsoft Tables',
            '6.\tSorting, Filtering Access Tables',
            '7.\tCreating Microsoft Access Queries',
            '8.\tExpression Builder',
            '9.\tCreating Forms',
            '-\tHow to make school database',
            '-\tChurch database',
            '10.\tCreating Reports',
            '-\tHow to make bank record',
            '-\tQuery',
            '-\tHow to make hospital record using Query',
            '-\tHow to get bill',
            '-\tThe run command',
            '-\tFiltering command',
            '-\tHow to filter out patients that suffered from a particular illness in a period of time',
            '11.\tExercises / Practices',

        ]
    },
    {
        name: 'MICROSOFT PUBLISHER',
        values: [
            '1.\tIntroduction to Microsoft Publisher',
            '-\tHistory, Functions, Versions and examples',
            '2.\tIntroduction to Microsoft Publisher Window',
            '-\tScreen features of Microsoft Publisher Window',
            '3.\tAdding text to a Publication',
            '4.\tFormatting and Wrapping Text',
            '5.\tConnecting Text Frames',
            '6.\tImporting',
            '7.\tAligning Objects',
            '8.\tUsing Backgrounds',
            '9.\tCreating Tables',
            '10.\tUsing Styles',
            '11.\tFormatting Frames',
            '12.\tUsing the Design Gallery',
            '13.\tPrinting your Publication',
            '14.\tExercises / Practice',
        ]

    },
]